<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lbl_Gender_Male</name>
   <tag></tag>
   <elementGuidId>bd6f8550-1528-4132-a289-197b1d0fe672</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>//label[normalize-space()='Male']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[normalize-space()='Male']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
