<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lbl_Gender_Female</name>
   <tag></tag>
   <elementGuidId>165eb43c-ca89-4393-b5ed-3c270a413cf8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>//label[normalize-space()='Female']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[normalize-space()='Female']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
