<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_LastName</name>
   <tag></tag>
   <elementGuidId>69a6f1df-2bf1-4307-872d-6842f1f4c780</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lastName</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
